// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectBalanceLibrary.Data;

#nullable disable

namespace ProjectBalanceLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ProjectBalanceLibrary.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("CopiesAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books", t =>
                        {
                            t.HasCheckConstraint("CK_Book_Copies", "CopiesAvailable <= TotalCopies AND CopiesAvailable >= 0 AND TotalCopies >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "John Steinbeck",
                            CopiesAvailable = 5,
                            ISBN = "9780140177398",
                            PublishedYear = 1937,
                            Title = "Of Mice and Men",
                            TotalCopies = 5
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.K. Rowling",
                            CopiesAvailable = 2,
                            ISBN = "9780439139595",
                            PublishedYear = 2000,
                            Title = "HP and the Goblet of Fire",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 3,
                            Author = "J.R.R. Tolkien",
                            CopiesAvailable = 1,
                            ISBN = "9780261103573",
                            PublishedYear = 1954,
                            Title = "The Lord of the Rings",
                            TotalCopies = 4
                        });
                });

            modelBuilder.Entity("ProjectBalanceLibrary.Models.Lender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lenders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@projectbalance.com",
                            FullName = "Alice Johnson"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@projectbalance.com",
                            FullName = "Bob Smith"
                        },
                        new
                        {
                            Id = 3,
                            Email = "cindy@projectbalance.com",
                            FullName = "Cindy Lee"
                        });
                });

            modelBuilder.Entity("ProjectBalanceLibrary.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LenderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LoanDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnDateUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("LenderId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("ProjectBalanceLibrary.Models.Loan", b =>
                {
                    b.HasOne("ProjectBalanceLibrary.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectBalanceLibrary.Models.Lender", "Lender")
                        .WithMany("Loans")
                        .HasForeignKey("LenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Lender");
                });

            modelBuilder.Entity("ProjectBalanceLibrary.Models.Book", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("ProjectBalanceLibrary.Models.Lender", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
